name: Terraform CI/CD with GitHub Secrets

on:
  push:
    branches:
      - development
      - master

jobs:
  terraform:
    name: Deploy to name: ${{ github.ref_name == 'master' && 'Production' || github.ref_name == 'development' && 'Development' || 'Unknown' }}
    runs-on: [self-hosted, terraform]

    environment:
      name: name: ${{ github.ref_name == 'master' && 'Production' || github.ref_name == 'development' && 'Development' || 'Unknown' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
        run: terraform apply -auto-approve
